Initial commit in openmp branch

diff --git a/src/setopts b/src/setopts
--- a/src/setopts
+++ b/src/setopts
@@ -32,12 +32,13 @@
 #   -q     query: prints report of options that are enabled / disabled.
 #   -h     help: prints a list of available options 
 #
-# The -d and -c options each enable or disable a feature. Each such
+# The -d, -c and -m options each enable or disable a feature. Each such
 # option takes 0 or 1 as a required argument, using 1 to denote "enable"
 # and 0 to denote "disable".
 #
 #   -d (0|1)   debugging           (defines/undefines UTIL_DEBUG)
 #   -c (0|1)   CUDA code           (defines/undefines PSCF_CUDA) 
+#   -m (0|1)   OpenMp code         (defines/undefines PSCF_OPENMP) 
 #
 # This -a option sets an identifier for the NVIDIA GPU architecture to be 
 # targeted by the NVIDIA CUDA compiler. The argument of this command line 
@@ -66,7 +67,7 @@
 #   >  ./setopts -c1  -a sm_70
 #
 #-----------------------------------------------------------------------
-while getopts "a:c:d:qh" opt; do
+while getopts "a:c:d:m:qh" opt; do
 
   if [ -n "$MACRO" ]; then 
     MACRO=""
@@ -90,6 +91,11 @@ while getopts "a:c:d:qh" opt; do
       VALUE=1
       FILE=config.mk
       ;;
+    m)
+      MACRO=PSCF_OPENMP
+      VALUE=1
+      FILE=config.mk
+      ;;
     q)
       if [ `grep "^ *UTIL_DEBUG *= *1" config.mk` ]; then
          echo "-d ON     - debugging" >&2
@@ -100,6 +106,11 @@ while getopts "a:c:d:qh" opt; do
          echo "-c ON     - CUDA compilation" >&2
       else
          echo "-c OFF    - CUDA compilation" >&2
+      fi
+      if [ `grep "^ *PSCF_OPENMP *= *1" config.mk` ]; then
+         echo "-c ON     - OPENMP compilation" >&2
+      else
+         echo "-c OFF    - OPENMP compilation" >&2
       fi
       ;;
     h)
@@ -123,12 +134,13 @@ while getopts "a:c:d:qh" opt; do
       echo "   -q   query: prints list of options that are enabled / disabled"
       echo "   -h   help: prints a list of available options"
       echo " "
-      echo " The -d and -c options each enable or disable a feature. Each"
-      echo " such option takes 0 or 1 as a required argument, using 1 to"
-      echo " enable and 0 to disable the feature"
+      echo " The -d, -c, and -m options each enable or disable a feature."
+      echo " Each such option takes 0 or 1 as a required argument, using 1"
+      echo " to enable and 0 to disable the feature"
       echo "  "
-      echo "   -d (0|1)   debugging           (defines/undefines UTIL_DEBUG)"
-      echo "   -c (0|1)   CUDA code           (defines/undefines PSCF_CUDA)"
+      echo "   -d (0|1)   debugging         (defines/undefines UTIL_DEBUG)"
+      echo "   -c (0|1)   CUDA code         (defines/undefines PSCF_CUDA)"
+      echo "   -c (0|1)   OpenMP code       (defines/undefines PSCF_OPENMP)"
       echo " "
       echo " The -a option sets an identifier for the NVIDIA GPU architecture"
       echo " to be targeted by the NVIDIA CUDA compiler. The argument of this"
